### ISSUE TITLE
Webpack production

### ISSUE THREAD

**Issue by SaboteurSpk** [martijnboland/VSReact#2]
Hello,
could You please add some readme part about getting and using production release? I'm able to get the index.html, main.js and vendor.js files in dist directory, but I'm not able to view the app using the index.html file.

The hot reload with development configuration works fine.
Thank You for Your work!

**Comment by mihir-harbinger** [comment]
Hi, can you provide some docs for creating production-ready bundle? I believe, we do not need to run webpack server at production. Am I correct? Am I supposed to use other port than 3000?

Thanks for creating this awesome boilerplate.

**Comment by martijnboland** [comment]
The production build creates a /dist directory that contains everything you'll need to run the app. This can be deployed to whatever static web server. You can even run it directly from the filesystem on your computer (file:///path-to-index-in-dist-directory.html)
